import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';
import './globals.css';

const quicksand = Quicksand({
  subsets: ['latin'],
  variable: '--font-quicksand',
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Midtrans Simulation',
  description: 'Generated by create next app',
};

import { Toaster } from 'react-hot-toast';
import { AuthProvider } from '../context/AuthContext';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} antialiased`}>
        <AuthProvider>
          <Toaster
            position="top-center"
            toastOptions={{
              className: 'bg-neutral-800 text-white border border-neutral-700',
              style: {
                background: '#262626',
                color: '#fff',
                border: '1px solid #404040',
              },
            }}
          />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
